name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install @parcel/watcher
        run: npm install @parcel/watcher --save-dev

      - name: Rebuild native modules
        run: npm rebuild

      - name: Verify installed modules
        run: ls -la node_modules/lightningcss

      - name: Ensure correct binary
        run: |
          npm install --platform=linux --arch=x64 @parcel/watcher
          npm install --platform=linux --arch=x64 lightningcss

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
